server:
    port: 8080
spring:
    application:
        name: task
    datasource:
        username: ${API_DB_USERNAME}
        password: ${API_DB_PASSWORD}
        url: jdbc:postgresql://postgres:5432/apidatabase
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
                jdbc:
                    "[batch_size]": 5
                    "[order_inserts]": true
                generate_statistics: false
        show-sql: false
youtube:
    api-key: ${API_KEY}