version: "3.3"

services:
    postgres:
      image: postgres
      container_name: postgres-local
      ports: 
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=sisedu
      volumes:
        - postgresql_data:/var/lib/postgresql/data
        - ../scripts/banco-dados/ddl/estudante.sql:/docker-entrypoint-initdb.d/1.sql
        - ../scripts/banco-dados/ddl/dominio.sql:/docker-entrypoint-initdb.d/2.sql
        - ../scripts/banco-dados/dml/insert/insert-tipo-responsavel.sql:/docker-entrypoint-initdb.d/3.sql
        - ../scripts/banco-dados/dml/insert/insert-estado.sql:/docker-entrypoint-initdb.d/4.sql
        - ../scripts/banco-dados/dml/insert/insert-cidade.sql:/docker-entrypoint-initdb.d/5.sql
        - ../scripts/banco-dados/dml/insert/insert-bairro.sql:/docker-entrypoint-initdb.d/6.sql
        - ../scripts/banco-dados/dml/insert/insert-sub-bairro.sql:/docker-entrypoint-initdb.d/7.sql
        - ../scripts/banco-dados/dml/insert/insert-escola.sql:/docker-entrypoint-initdb.d/8.sql
      networks:
        - postgres_network
        
volumes:
    postgresql_data:

networks: 
    postgres_network:
      driver: bridge